full_data<-read.csv("Documents/coursera/reproducible research/steps_data/activity.csv")
full_data$date<-as.Date(levels(full_data$date)[full_data$date])
total_steps_a_day<-aggregate(steps~date,full_data,sum,na.rm=T)
head(total_steps_a_day)
tail(total_steps_a_day)
#Histogram of total steps taken per day
png("plot1.png")
hist(total_steps_a_day$steps,xlab = "Total steps taken each day",main="Histogram of total steps taken each day")
dev.off()
mean_data<-aggregate(steps~interval,full_data,mean)
png("plot2.png")
plot(mean_data$interval,mean_data$steps,type = "l",xlab = "Interval",ylab = "Mean number of steps",main = "Mean number of steps per day by interval")
dev.off()
index<-which(is.na(full_data$steps))
mean_steps<-with(full_data,tapply(steps,interval,mean,na.rm=T))
m<-mean(mean_steps,na.rm = T)
for(i in 1:length(index)){
    full_data[index[i],1]<-m
}
total_steps_a_day<-aggregate(steps~date,full_data,sum,na.rm=T)
png("plot3.png")
hist(total_steps_a_day$steps,xlab = "Total steps taken each day",main="Histogram of total steps taken each day")
dev.off()
library(dplyr)
full_data<- mutate(full_data, day = ifelse(weekdays(full_data$date) == "Saturday" | weekdays(full_data$date) == "Sunday", "weekend", "weekday"))
full_data$day<-as.factor(full_data$day)
data_weekend<-subset(full_data,full_data$day=="weekend")
data_weekday<-subset(full_data,full_data$day=="weekday")
mean_steps_weekend<-tapply(data_weekend$steps,data_weekend$interval,mean)
mean_steps_weekday<-tapply(data_weekday$steps,data_weekday$interval,mean)
weekend<-unique(data_weekend$interval)
weekday<-unique(data_weekday$interval)
final_weekend<-data.frame(cbind(mean_steps_weekend,weekend))
final_weekday<-data.frame(cbind(mean_steps_weekday,weekday))
png("plot4.png")
par(mfrow=c(2,1),mar=c(4,4,2,1))
plot(final_weekend$weekend,final_weekend$mean_steps_weekend,type = "l",xlab = "Intervals",ylab = "Average Steps",main = "Weekend",xlim = c(0,2500),ylim = c(0,200))
plot(final_weekday$weekday,final_weekday$mean_steps_weekday,type = "l",xlab = "Intervals",ylab = "Average Steps",main = "Weekday",xlim = c(0,2500),ylim = c(0,200))
dev.off()